export const dependants = [
  {
    id: 1,
    name: 'Jorrie Clowley',
    age: 1,
    relation: 'Son',
    lastVisit: '12/10/2023',
    provider: 'Quigley Group',
    amount: '₵ 274.44',
    status: false,
  },
  {
    id: 2,
    name: 'Raviv Faire',
    age: 2,
    relation: 'Father',
    lastVisit: '5/4/2024',
    provider: 'Kuphal, Herman and Muller',
    amount: '₵ 173.84',
    status: false,
  },
  {
    id: 3,
    name: 'Micheil Jendas',
    age: 3,
    relation: 'Son',
    lastVisit: '7/12/2023',
    provider: 'Schuster Inc',
    amount: '₵ 79.91',
    status: false,
  },
  {
    id: 4,
    name: 'Cinderella Dawidman',
    age: 4,
    relation: 'Spouse',
    lastVisit: '6/28/2023',
    provider: 'Dietrich, Barton and Daugherty',
    amount: '₵ 53.96',
    status: true,
  },
  {
    id: 5,
    name: 'Mair Hafner',
    age: 5,
    relation: 'Son',
    lastVisit: '1/29/2024',
    provider: 'Sauer and Sons',
    amount: '₵ 125.48',
    status: true,
  },
  {
    id: 6,
    name: 'Margy Aldham',
    age: 6,
    relation: 'Father',
    lastVisit: '6/29/2023',
    provider: 'Toy-Kunze',
    amount: '₵ 155.51',
    status: true,
  },
  {
    id: 7,
    name: 'Cicily Dockree',
    age: 7,
    relation: 'Father',
    lastVisit: '5/22/2023',
    provider: 'Brakus Group',
    amount: '₵ 67.37',
    status: true,
  },
  {
    id: 8,
    name: 'Jayson Peters',
    age: 8,
    relation: 'Mother',
    lastVisit: '11/9/2023',
    provider: 'Kreiger-Lockman',
    amount: '₵ 139.39',
    status: true,
  },
  {
    id: 9,
    name: 'Deny Polglaze',
    age: 9,
    relation: 'Father',
    lastVisit: '10/13/2023',
    provider: 'Predovic, Raynor and Nicolas',
    amount: '₵ 281.25',
    status: false,
  },
  {
    id: 10,
    name: 'Berthe Taberner',
    age: 10,
    relation: 'Son',
    lastVisit: '7/4/2023',
    provider: 'Simonis-Paucek',
    amount: '₵ 279.02',
    status: false,
  },
];
