export const dependants = [
  {
    id: 1,
    name: 'Jorrie Clowley',
    age: 1,
    relation: 'Son',
    lastVisit: '12/10/2023',
    provider: 'Quigley Group',
    amount: '$274.44',
    status: false,
  },
  {
    id: 2,
    name: 'Raviv Faire',
    age: 2,
    relation: 'Father',
    lastVisit: '5/4/2024',
    provider: 'Kuphal, Herman and Muller',
    amount: '$173.84',
    status: false,
  },
  {
    id: 3,
    name: 'Micheil Jendas',
    age: 3,
    relation: 'Son',
    lastVisit: '7/12/2023',
    provider: 'Schuster Inc',
    amount: '$79.91',
    status: false,
  },
  {
    id: 4,
    name: 'Cinderella Dawidman',
    age: 4,
    relation: 'Spouse',
    lastVisit: '6/28/2023',
    provider: 'Dietrich, Barton and Daugherty',
    amount: '$53.96',
    status: true,
  },
  {
    id: 5,
    name: 'Mair Hafner',
    age: 5,
    relation: 'Son',
    lastVisit: '1/29/2024',
    provider: 'Sauer and Sons',
    amount: '$125.48',
    status: true,
  },
  {
    id: 6,
    name: 'Margy Aldham',
    age: 6,
    relation: 'Father',
    lastVisit: '6/29/2023',
    provider: 'Toy-Kunze',
    amount: '$155.51',
    status: true,
  },
  {
    id: 7,
    name: 'Cicily Dockree',
    age: 7,
    relation: 'Father',
    lastVisit: '5/22/2023',
    provider: 'Brakus Group',
    amount: '$67.37',
    status: true,
  },
  {
    id: 8,
    name: 'Jayson Peters',
    age: 8,
    relation: 'Mother',
    lastVisit: '11/9/2023',
    provider: 'Kreiger-Lockman',
    amount: '$139.39',
    status: true,
  },
  {
    id: 9,
    name: 'Deny Polglaze',
    age: 9,
    relation: 'Father',
    lastVisit: '10/13/2023',
    provider: 'Predovic, Raynor and Nicolas',
    amount: '$281.25',
    status: false,
  },
  {
    id: 10,
    name: 'Berthe Taberner',
    age: 10,
    relation: 'Son',
    lastVisit: '7/4/2023',
    provider: 'Simonis-Paucek',
    amount: '$279.02',
    status: false,
  },
  {
    id: 11,
    name: 'Loren Minall',
    age: 11,
    relation: 'Son',
    lastVisit: '11/4/2023',
    provider: 'Cartwright Group',
    amount: '$150.91',
    status: true,
  },
  {
    id: 12,
    name: 'Levon Shee',
    age: 12,
    relation: 'Son',
    lastVisit: '10/25/2023',
    provider: 'Walter, Kshlerin and Moore',
    amount: '$241.88',
    status: false,
  },
  {
    id: 13,
    name: 'Madelle Darte',
    age: 13,
    relation: 'Son',
    lastVisit: '9/21/2023',
    provider: 'Tromp, Strosin and McGlynn',
    amount: '$72.74',
    status: false,
  },
  {
    id: 14,
    name: 'Honey Scheu',
    age: 14,
    relation: 'Mother',
    lastVisit: '10/21/2023',
    provider: 'Lebsack and Sons',
    amount: '$264.09',
    status: true,
  },
  {
    id: 15,
    name: 'Feodor De Bruyn',
    age: 15,
    relation: 'Spouse',
    lastVisit: '5/8/2024',
    provider: 'Terry Inc',
    amount: '$265.86',
    status: true,
  },
  {
    id: 16,
    name: 'Peadar Zoellner',
    age: 16,
    relation: 'Mother',
    lastVisit: '11/9/2023',
    provider: 'Stoltenberg-Lockman',
    amount: '$107.18',
    status: true,
  },
  {
    id: 17,
    name: 'Vergil MacIllrick',
    age: 17,
    relation: 'Mother',
    lastVisit: '7/8/2023',
    provider: 'Beatty, Stroman and Hodkiewicz',
    amount: '$82.82',
    status: true,
  },
  {
    id: 18,
    name: 'Thadeus Culligan',
    age: 18,
    relation: 'Father',
    lastVisit: '2/18/2024',
    provider: 'Schultz Inc',
    amount: '$193.38',
    status: false,
  },
  {
    id: 19,
    name: 'Loria Theuss',
    age: 19,
    relation: 'Mother',
    lastVisit: '12/5/2023',
    provider: 'Jerde LLC',
    amount: '$107.55',
    status: true,
  },
  {
    id: 20,
    name: 'Randy Wharby',
    age: 20,
    relation: 'Son',
    lastVisit: '8/28/2023',
    provider: 'Lindgren Group',
    amount: '$292.63',
    status: true,
  },
  {
    id: 21,
    name: 'Ezri Thay',
    age: 21,
    relation: 'Father',
    lastVisit: '11/26/2023',
    provider: 'Wuckert Inc',
    amount: '$180.53',
    status: true,
  },
  {
    id: 22,
    name: 'Chick Barens',
    age: 22,
    relation: 'Mother',
    lastVisit: '2/21/2024',
    provider: 'Klocko, Lynch and Heaney',
    amount: '$255.50',
    status: true,
  },
  {
    id: 23,
    name: 'Binni Jaffra',
    age: 23,
    relation: 'Daughter',
    lastVisit: '9/22/2023',
    provider: 'Halvorson, Braun and Corkery',
    amount: '$203.68',
    status: true,
  },
  {
    id: 24,
    name: 'Carmelina Sheirlaw',
    age: 24,
    relation: 'Daughter',
    lastVisit: '4/28/2024',
    provider: 'Kuphal Inc',
    amount: '$232.53',
    status: false,
  },
  {
    id: 25,
    name: 'Etienne Dudding',
    age: 25,
    relation: 'Father',
    lastVisit: '1/30/2024',
    provider: 'Jenkins and Sons',
    amount: '$266.49',
    status: false,
  },
  {
    id: 26,
    name: 'Norry Lantoph',
    age: 26,
    relation: 'Mother',
    lastVisit: '6/23/2023',
    provider: 'Aufderhar, Bernier and Marvin',
    amount: '$87.12',
    status: true,
  },
  {
    id: 27,
    name: 'Rayshell Thoms',
    age: 27,
    relation: 'Son',
    lastVisit: '9/28/2023',
    provider: 'Marquardt-Wyman',
    amount: '$200.26',
    status: true,
  },
  {
    id: 28,
    name: 'Federica De Paoli',
    age: 28,
    relation: 'Son',
    lastVisit: '12/28/2023',
    provider: 'Green, Rolfson and Russel',
    amount: '$150.82',
    status: true,
  },
  {
    id: 29,
    name: 'Merissa Rodenborch',
    age: 29,
    relation: 'Daughter',
    lastVisit: '1/2/2024',
    provider: 'Funk Group',
    amount: '$250.01',
    status: true,
  },
  {
    id: 30,
    name: 'Tybalt Rushforth',
    age: 30,
    relation: 'Daughter',
    lastVisit: '11/5/2023',
    provider: 'Hackett Inc',
    amount: '$69.51',
    status: true,
  },
  {
    id: 31,
    name: 'Ryon Grimme',
    age: 31,
    relation: 'Father',
    lastVisit: '11/4/2023',
    provider: 'Rath-Bernhard',
    amount: '$119.92',
    status: true,
  },
  {
    id: 32,
    name: 'Pam Gilkison',
    age: 32,
    relation: 'Spouse',
    lastVisit: '9/15/2023',
    provider: 'Stoltenberg and Sons',
    amount: '$107.48',
    status: false,
  },
  {
    id: 33,
    name: 'Davis Heymes',
    age: 33,
    relation: 'Father',
    lastVisit: '4/27/2024',
    provider: 'Simonis-Langworth',
    amount: '$286.47',
    status: false,
  },
  {
    id: 34,
    name: 'Evelin Kitchingman',
    age: 34,
    relation: 'Mother',
    lastVisit: '8/17/2023',
    provider: 'Botsford Group',
    amount: '$164.16',
    status: true,
  },
  {
    id: 35,
    name: 'Marlie Fardell',
    age: 35,
    relation: 'Son',
    lastVisit: '2/4/2024',
    provider: 'Simonis-Waelchi',
    amount: '$59.41',
    status: true,
  },
  {
    id: 36,
    name: 'Marc Dudbridge',
    age: 36,
    relation: 'Father',
    lastVisit: '11/16/2023',
    provider: 'Rau LLC',
    amount: '$180.34',
    status: false,
  },
  {
    id: 37,
    name: 'Eada Ambrosio',
    age: 37,
    relation: 'Spouse',
    lastVisit: '5/8/2024',
    provider: 'Kunde, Bogisich and Nikolaus',
    amount: '$211.73',
    status: true,
  },
  {
    id: 38,
    name: 'Norina Flaune',
    age: 38,
    relation: 'Daughter',
    lastVisit: '8/21/2023',
    provider: 'Johnston and Sons',
    amount: '$234.12',
    status: false,
  },
  {
    id: 39,
    name: 'Bernardo Berzen',
    age: 39,
    relation: 'Spouse',
    lastVisit: '9/6/2023',
    provider: 'Murray-Dicki',
    amount: '$220.41',
    status: true,
  },
  {
    id: 40,
    name: 'Jacinta Cullrford',
    age: 40,
    relation: 'Spouse',
    lastVisit: '1/6/2024',
    provider: 'Bogisich LLC',
    amount: '$179.67',
    status: true,
  },
  {
    id: 41,
    name: 'Delmar Massingham',
    age: 41,
    relation: 'Daughter',
    lastVisit: '2/13/2024',
    provider: 'Hansen Inc',
    amount: '$236.73',
    status: true,
  },
  {
    id: 42,
    name: 'Juliane Joyes',
    age: 42,
    relation: 'Mother',
    lastVisit: '9/30/2023',
    provider: 'Gerhold and Sons',
    amount: '$231.72',
    status: true,
  },
  {
    id: 43,
    name: 'Bryana McGeneay',
    age: 43,
    relation: 'Father',
    lastVisit: '11/13/2023',
    provider: 'Marks, Schoen and Spencer',
    amount: '$193.14',
    status: false,
  },
  {
    id: 44,
    name: 'Perry Huson',
    age: 44,
    relation: 'Son',
    lastVisit: '6/27/2023',
    provider: 'Herman and Sons',
    amount: '$101.21',
    status: true,
  },
  {
    id: 45,
    name: 'Brandtr Lavery',
    age: 45,
    relation: 'Mother',
    lastVisit: '10/8/2023',
    provider: 'Torphy Group',
    amount: '$269.46',
    status: false,
  },
  {
    id: 46,
    name: 'Shoshanna Tertre',
    age: 46,
    relation: 'Mother',
    lastVisit: '12/13/2023',
    provider: 'Connelly and Sons',
    amount: '$298.52',
    status: true,
  },
  {
    id: 47,
    name: 'Terrye Boatswain',
    age: 47,
    relation: 'Spouse',
    lastVisit: '12/1/2023',
    provider: 'Mann Group',
    amount: '$224.60',
    status: true,
  },
  {
    id: 48,
    name: 'Antoine Steanyng',
    age: 48,
    relation: 'Son',
    lastVisit: '4/28/2024',
    provider: 'Walter Group',
    amount: '$220.77',
    status: false,
  },
  {
    id: 49,
    name: 'Gayle McKaile',
    age: 49,
    relation: 'Spouse',
    lastVisit: '7/13/2023',
    provider: 'Heaney Inc',
    amount: '$134.65',
    status: true,
  },
  {
    id: 50,
    name: 'Esme Nanson',
    age: 50,
    relation: 'Mother',
    lastVisit: '4/19/2024',
    provider: 'Jacobson and Sons',
    amount: '$141.85',
    status: false,
  },
];
